type: S3
config:
  bucket: "thanos"
  endpoint: 'minio-service.default.svc.cluster.local:9000'
  access_key: "minio"
  insecure: true
  signature_version2: false
  encrypt_sse: false
  secret_key: "minio123"
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: true
  trace:
    enable: false
  part_size: 134217728
